[build]
  command = "npm run build"
  publish = "out" # plugin handles this, but fallback is nice

[build.environment]
  NODE_VERSION = "18.17.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-emails"

[functions]
  directory = "netlify/functions"
