"use server"

import { createServerActionClient } from "@supabase/auth-helpers-nextjs"
import { cookies } from "next/headers"
import { revalidatePath } from "next/cache"

interface ProductData {
  name: string
  price: string
  description?: string
  image?: string
  is_on_sale?: boolean // Added
  sale_price?: number | null // Added
  sale_percent?: number | null // Added
  tag?: string // Added
  category?: string // Added
  is_most_sold?: boolean // Added
  sku?: string // Added for type safety, but will be handled
}

export async function createProduct(_: any, formData: ProductData) {
  const supabase = createServerActionClient({ cookies })
  const dataToInsert = { ...formData };
  // Remove sku from the payload for new products, as it's auto-generated by a DB trigger
  if (dataToInsert.sku === "" || dataToInsert.sku === null || dataToInsert.sku === undefined) {
    delete dataToInsert.sku;
  }
  const { error } = await supabase.from("products").insert([dataToInsert])
  if (error) {
    return { error: error.message }
  }
  revalidatePath("/admin/products")
  revalidatePath("/shop")
  revalidatePath("/") // Revalidate homepage
  return { error: null }
}

export async function updateProduct(id: number | undefined, formData: ProductData) {
  if (!id) return { error: "Product ID is missing." }
  const supabase = createServerActionClient({ cookies })
  const dataToUpdate = { ...formData };
  // Ensure SKU is not updated manually, as it's auto-generated and should be immutable
  delete dataToUpdate.sku; // Remove SKU from update payload
  const { error } = await supabase.from("products").update(dataToUpdate).eq("id", id)
  if (error) {
    return { error: error.message }
  }
  revalidatePath("/admin/products")
  revalidatePath(`/product/${id}`)
  revalidatePath("/shop")
  revalidatePath("/") // Revalidate homepage
  return { error: null }
}

export async function deleteProduct(id: number) {
  const supabase = createServerActionClient({ cookies })
  const { error } = await supabase.from("products").delete().eq("id", id)
  if (error) {
    return { error: error.message }
  }
  revalidatePath("/admin/products")
  revalidatePath("/shop")
  revalidatePath("/") // Revalidate homepage
  return { error: null }
}