INSERT INTO public.products (id, name, description, price, image, is_digital, download_url, sale_price, is_on_sale, sale_percent)
VALUES
(1, 'Microsoft Office 2021 Pro Plus', 'Get the essential tools for productivity with Microsoft Office 2021 Professional Plus. Includes Word, Excel, PowerPoint, Outlook, and more.', '299.99', '/images/office-2021.png', TRUE, 'https://example.com/downloads/office2021.zip', '199.99', TRUE, 33.33),
(2, 'Windows 11 Pro OEM Key', 'Upgrade to the latest Windows operating system with a genuine Windows 11 Pro OEM key. Enhanced security and features for professionals.', '199.99', '/images/windows-11.png', TRUE, 'https://example.com/downloads/windows11.zip', NULL, FALSE, NULL),
(3, 'Adobe Photoshop 2024 License', 'Unleash your creativity with Adobe Photoshop 2024. The industry-standard for image manipulation and graphic design.', '599.99', '/images/photoshop-2024.png', TRUE, 'https://example.com/downloads/photoshop2024.zip', '449.99', TRUE, 25.00),
(4, 'Kaspersky Total Security 2024 (1 Year)', 'Comprehensive protection for your digital life. Kaspersky Total Security offers antivirus, anti-malware, and privacy tools.', '79.99', '/images/kaspersky-total-security.png', TRUE, 'https://example.com/downloads/kaspersky.zip', NULL, FALSE, NULL),
(5, 'Visual Studio 2022 Enterprise', 'The ultimate IDE for developers. Visual Studio 2022 Enterprise provides a complete set of tools for building modern applications.', '1199.99', '/images/visual-studio-2022.png', TRUE, 'https://example.com/downloads/visualstudio2022.zip', NULL, FALSE, NULL),
(6, 'AutoCAD 2024 Subscription (1 Year)', 'Industry-leading CAD software for 2D and 3D design. AutoCAD 2024 helps you create stunning designs with precision.', '1775.00', '/images/autocad-2024.png', TRUE, 'https://example.com/downloads/autocad2024.zip', '1499.00', TRUE, 15.55),
(7, 'ESET Internet Security (3 Devices, 1 Year)', 'Advanced multi-layered protection for your everyday online use. ESET Internet Security protects your privacy and data.', '69.99', '/images/eset-internet-security.png', TRUE, 'https://example.com/downloads/eset.zip', NULL, FALSE, NULL),
(8, 'Grammarly Premium (1 Year)', 'Write with confidence. Grammarly Premium helps you compose bold, clear, mistake-free writing.', '139.99', '/images/grammarly-premium.png', TRUE, 'https://example.com/downloads/grammarly.zip', NULL, FALSE, NULL);