// This file is automatically generated. Do not edit it directly.
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClientComponentClient();